test_vagrant_volume:

    # optional SOCKS proxy
    socks_host: ""
    socks_port: 9150

    # SSH host, port, user
    host: "localhost"
    port: 2422
    user: root
    password: "root"
    auth_method: password

    # SSH options
    ssh_tcp_timeout: 300
    ssh_banner_timeout: 120
    ssh_auth_timeout: 300
    verify_ssh_fingerprint: true # use "false" ONLY for testing, never use "false" on production

    # public key, and your passphrase to the public key
    public_key: ""
    passphrase: ""

    checksum_method: "sha256sum"
    on_security_violation: "echo 'Checksum failed... unmounting secure data disk, waiting for administrator intervention...'"

    checksum_files:
        sh: '/bin/sh'
        bash: '/bin/bash'
        losetup: '$(whereis losetup|awk "{print \$2}")'

    healthchecks:
        - command: "ps aux |grep SOOOMETHING"
          on_failure: "echo 'Something on failure'"

          # Set to false if you do not want to execute commands from "on_failure" when checksum security violation was detected
          on_failure_even_if_security_violation: false

        - command: "ps aux |grep ON_VIOLATION_WILL_EXECUTE"
          on_failure: "echo 'Something on failure - on_failure_even_if_security_violation: true'"
          on_failure_even_if_security_violation: true

        - command: "ps aux |grep bash"
          on_failure: "echo 'This should not show'"
          on_failure_even_if_security_violation: false
